### PR TITLE
Replace dots in cron file names with underscores

### LINKED ISSUE #2: Cron.d files with dots are ignored on debian
Cron files under /etc/cron.d are silently ignored for hosts with dots in their name. This seems to be a debian/ubuntu specific issue.

### PR DESCRIPTION
**Pull request by runejuhl**
Fixes #2.

### CODE REVIEW

**Comment by loomsen** [comment]
Hi @runejuhl 

Thank you for your contribution! I will gladly merge your pull request if you add a section, which makes sure current files with dots are removed. Otherwise, centos users updating would probably have their backup jobs running twice. 
Could you please check that by running the current version, creating the files with dots, then updating to your version, and running puppet again?

I'm fine with it if you add a section where you make sure those files are absent.

Thank you.

**Comment by loomsen** [comment]
Sorry, closed by mistake.

**Comment by loomsen** [comment]
Also, this:
`
+    $cronfile = regsubst("${cron_dir}/${host}", '\.', '_')
￼`
seems to also substitute the dot in `/etc/cron.d`, doesn't it? :)

**Comment by runejuhl** [comment]
Yes, it would indeed fail -- sorry about that :)

Do you want me to prepend something like `rsnapshot_` to the cron file name while we're at it? The current naming scheme is not quite as transparent as I'd like...

I don't have time for testing it tonight, but I'll do it tomorrow and fix any leftover issues.

**Comment by loomsen** [comment]
Sure, feel free. Just make sure to remove any leftovers :)
Thank you!

**Comment by loomsen** [comment]
Oh, and it would be very kind if you could also add a section to the README explaining what you did :) 
And maybe a note at the top telling people that their files will be renamed.
:+1:

**Comment by loomsen** [comment]
About the naming, my second thought is you could add an optional $filename_prefix parameter, which should be empty by default. So cronfile would then look something like:
```
$cronfile = "${cron_dir}/${filename_prefix}${host}
```
But this is more of a feature request. I will gladly add your code if you want to go that way. 
Please also add this to the README if you do :)

**Comment by runejuhl** [comment]
@loomsen Sorry for dragging this out -- just wanted to let you know that I'll get around to this within a few days :)

**Comment by loomsen** [comment]
No hurries, I'm pretty busy atm as well :)

**Comment by monotek** [comment]
Fixed in https://github.com/loomsen/puppet-rsnapshot/pull/7

**Comment by runejuhl** [comment]
Closing this in favor of #7 from @monotek :)

**Pull request closed without merging**
